const postData= [
    {
    title:'India and Nepal' ,
    category: 'culture trip',
    description: 'We spent one month in Nepal volunteering for Home and hope and working with orphant children',
    username: "Mariela" ,
    selectedFile: 0,
    likes:0,
    // img:
},
{
    title:'Alaska',
    category: 'mountain',
    description: 'trip to Denali National park and mount Denali',
    username: 'Mariela',
    selectedFile:0 ,
    likes:0,
},
{
    title: 'Equador',
    category: 'city and culture',
    description: 'Visited Quito, Manta, Esmeraldas',
    username: 'Mariela',
    selectedFile: 0,
    likes:0,
},
{
    title: 'Riviera Maya, Mexico'  ,
    category: 'beach' ,
    description:"Wedding at Barcelo, Riviera Maya and Vacation with family and friends",
    username: 'Mariela',
    selectedFile: 0,
    likes:0,
},
{
    title: 'Japan',
    category: 'city',
    description: 'New Year in Tokyo',
    username: 'Mariela',
    selectedFile:0,
    likes:0,
},
{
    title: 'Mauritus' ,
    category:'beach' ,
    description: 'Family facation with sister and family',
    username: 'Mariela',
    selectedFile:0 ,
    likes:0,
},
{
    title: 'Beijing, China',
    category: 'city, culture',
    description: 'Vacation with in-laws',
    username:'Mariela',
    selectedFile: 0,
    likes:0,
},
{
    title:'Glacier National Park' ,
    category: 'mountain',
    description: "My 30th birthday",
    username: 'Mariela',
    selectedFile:0 ,
    likes:0,
},
{
    title:'Easter Island' ,
    category: 'beach',
    description: 'The most remote place on Earth',
    username: 'Mariela',
    selectedFile:0 ,
    likes:0,
},
{
    title: 'Paris-London trip',
    category: 'city, culture',
    description: 'Visit to Stonehendge, museums and pasty shops',
    username: 'Mariela',
    selectedFile:0 ,
    likes:0,
},
{
    title: 'Cydney',
    category:'city' ,
    description: 'Visited Australia for first time.',
    username: 'Mariela' ,
    selectedFile:0 ,
    likes:0,
},
{
    title:"Great Pyramids of Giza" ,
    category: 'culture and city',
    description: '"Visited Egypt for fist time',
    username: 'Mariela',
    selectedFile: 0,
    likes:0,
},
// {
//     title: ,
//     category: ,
//     description ,
//     username: ,
//     selectedFile: ,
//     likes:0,
// },
// {
//     title: ,
//     category: ,
//     description ,
//     username: ,
//     selectedFile: ,
//     likes:0,
// },
// {
//     title: ,
//     category: ,
//     description ,
//     username: ,
//     selectedFile: ,
//     likes:0,
// },
// {
//     title: ,
//     category: ,
//     description ,
//     username: ,
//     selectedFile: ,
//     likes:0,
// }
]

module.exports = postData;