const postData= [
    {
    title:'India and Nepal' ,
    category: 'culture trip',
    describtion: 'We spent one month in Nepal volunteering for Home and hope and working with orphant children',
    user: "Mariela" ,
    selectedFile: 0,
    likes:0,
},
{
    title:'Alaska',
    category: 'mountain',
    describtion: 'trip to Denali National park and mount Denali',
    user: 'Mariela',
    selectedFile:0 ,
    likes:0,
},
{
    title: 'Equador',
    category: 'city and culture',
    describtion: 'Visited Quito, Manta, Esmeraldas',
    user: 'Mariela',
    selectedFile: 0,
    likes:0,
},
{
    title: 'Riviera Maya, Mexico'  ,
    category: 'beach' ,
    describtion:"Wedding at Barcelo, Riviera Maya and Vacation with family and friends",
    user: 'Mariela',
    selectedFile: 0,
    likes:0,
},
{
    title: 'Japan',
    category: 'city',
    describtion: 'New Year in Tokyo',
    user: 'Mariela',
    selectedFile:0,
    likes:0,
},
{
    title: 'Mauritus' ,
    category:'beach' ,
    describtion: 'Family facation with sister and family',
    user: 'Mariela',
    selectedFile:0 ,
    likes:0,
},
{
    title: 'Beijing, China',
    category: 'city, culture',
    describtion: 'Vacation with in-laws',
    user:'Mariela',
    selectedFile: 0,
    likes:0,
},
{
    title:'Glacier National Park' ,
    category: 'mountain',
    describtion: "My 30th birthday",
    user: 'Mariela',
    selectedFile:0 ,
    likes:0,
},
{
    title:'Easter Island' ,
    category: 'beach',
    describtion: 'The most remote place on Earth',
    user: 'Mariela',
    selectedFile:0 ,
    likes:0,
},
{
    title: 'Paris-London trip',
    category: 'city, culture',
    describtion: 'Visit to Stonehendge, museums and pasty shops',
    user: 'Mariela',
    selectedFile:0 ,
    likes:0,
},
{
    title: 'Cydney',
    category:'city' ,
    describtion: 'Visited Australia for first time.',
    user: 'Mariela' ,
    selectedFile:0 ,
    likes:0,
},
{
    title:"Great Pyramids of Giza" ,
    category: 'culture and city',
    describtion: '"Visited Egypt for fist time',
    user: 'Mariela',
    selectedFile: 0,
    likes:0,
},
// {
//     title: ,
//     category: ,
//     describtion: ,
//     user: ,
//     selectedFile: ,
//     likes:0,
// },
// {
//     title: ,
//     category: ,
//     describtion: ,
//     user: ,
//     selectedFile: ,
//     likes:0,
// },
// {
//     title: ,
//     category: ,
//     describtion: ,
//     user: ,
//     selectedFile: ,
//     likes:0,
// },
// {
//     title: ,
//     category: ,
//     describtion: ,
//     user: ,
//     selectedFile: ,
//     likes:0,
// }
]

module.exports = postData;